### ISSUE TITLE
Directive contains its own form-tag

### ISSUE THREAD

**Issue by karlwestin** [eHealthAfrica/angular-eha.date-of-birth-or-age#5]
https://github.com/eHealthAfrica/angular-eha.date-of-birth-or-age/blob/master/src/date-of-birth-or-age.directive.tpl.html#L2

**Comment by tthew** [comment]
Just needs to be changed to a `div[ng-form]`

**Comment by tthew** [comment]
Actually it's even easier. We just need to remove the form tag altogether.
